window.templateSurvey = {
  "Receiving": [
    { "name": "Direct and clear", "rating": null },
    { "name": "Playful and teasing", "rating": null },
    { "name": "Gentle and nurturing", "rating": null },
    { "name": "Commanding and firm", "rating": null },
    { "name": "Quiet and observant", "rating": null },
    { "name": "Instructive / teacher-like", "rating": null },
    { "name": "Emotionally intense", "rating": null },
    { "name": "Dismissive / withholding", "rating": null },
    { "name": "Mocking / sarcastic", "rating": null },
    { "name": "Blunt / tactless", "rating": null },
    { "name": "Predatory / hunting tone", "rating": null, "roles": ["prey"] },
    { "name": "Stalking or circling speech", "rating": null, "roles": ["prey"] },
    { "name": "You’re mine / control language", "rating": null, "roles": ["prey"] },
    { "name": "Threatening (consensual)", "rating": null, "roles": ["prey"] },
    { "name": "Verbal cornering / coaxing", "rating": null, "roles": ["prey"] },
    { "name": "Watching you unravel", "rating": null, "roles": ["prey"] },
    { "name": "Cruel and cutting", "rating": null, "roles": ["sadist"] },
    { "name": "Psychological baiting", "rating": null, "roles": ["sadist"] },
    { "name": "Brat-breaking language", "rating": null, "roles": ["sadist"] },
    { "name": "Mock affection", "rating": null, "roles": ["sadist"] },
    { "name": "Shaming or emotional edge", "rating": null, "roles": ["sadist"] },
    { "name": "Disappointed dom voice", "rating": null, "roles": ["brat"] },
    { "name": "Mild scolding / mocking affection", "rating": null, "roles": ["brat"] },
    { "name": "Verbal power struggle", "rating": null, "roles": ["brat"] },
    { "name": "Challenge-response dynamics", "rating": null, "roles": ["brat"] },
    { "name": "Warm tone with expectation", "rating": null, "roles": ["caregiver"] },
    { "name": "Nurturing dominance", "rating": null, "roles": ["caregiver"] },
    { "name": "Reassuring commands", "rating": null, "roles": ["caregiver"] },
    { "name": "Obedient pet responses", "rating": null, "roles": ["pet"] },
    { "name": "Affectionate whimpering", "rating": null, "roles": ["pet"] }
  ]
};
