window.templateSurvey = {
  "Giving": [ { "name": "Licking", "rating": null } ],
  "Receiving": [ { "name": "Licking", "rating": null } ],
  "General": [
    { "name": "Temperature play", "rating": null },
    { "name": "Navel play", "rating": null },
    { "name": "Belly fucking", "rating": null },
    { "name": "Begging", "rating": null },
    { "name": "Fear play", "rating": null },
    { "name": "Masochism (general)", "rating": null },
    { "name": "Psychological masochism", "rating": null },
    { "name": "Sadism (general)", "rating": null },
    { "name": "Psychological sadism", "rating": null },
    { "name": "Resistance play", "rating": null },
    { "name": "Obedience training", "rating": null },
    { "name": "Manipulation", "rating": null },
    { "name": "Mind games", "rating": null },
    { "name": "Intelligence kink", "rating": null },
    { "name": "Service dynamics", "rating": null },
    { "name": "Power exchange", "rating": null },
    { "name": "Rituals and protocol", "rating": null },
    { "name": "Dehumanization", "rating": null },
    { "name": "Humiliation (general)", "rating": null },
    { "name": "Emotional edge", "rating": null },
    { "name": "Verbal play (general)", "rating": null },
    { "name": "Praise kink", "rating": null },
    { "name": "Shame kink", "rating": null },
    { "name": "Ownership", "rating": null },
    { "name": "Sensory play", "rating": null }
  ]
};
