window.__TK_EMBEDDED_CATEGORIES__ = [
  "Appearance Play",
  "Behavioral Play",
  "Body Fluids and Functions",
  "Body Modification",
  "Body Part / Fetish Play",
  "Body Part Torture",
  "Bondage and Suspension",
  "Breath Play",
  "Chastity Devices",
  "Communication",
  "Cosplay & Identity Play",
  "Gender Play & Transformation",
  "Headspace & Regression",
  "High-Intensity Kinks (SSC-Aware)",
  "Impact Play",
  "Medical Play",
  "Mindfuck & Manipulation",
  "Mouth Play",
  "Orgasm Control & Sexual Manipulation",
  "Other",
  "Performance & Internal Struggle",
  "Pet Play",
  "Primal & Bratting",
  "Protocol and Ritual",
  "Psychological Primal / Prey",
  "Psychology Play",
  "Relationship Preferences",
  "Roleplaying",
  "Sensation Play",
  "Service and Restrictive Behaviour",
  "Sexual Activity",
  "Shibari & Rope Bondage",
  "Virtual & Long-Distance Play",
  "Voyeurism/Exhibitionism",
  "Breeding"
]
;
